repository:
  description: scaffolder sub-command for commander
  homepage: https://npm.im/@travi/scaffolder-sub-command
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: bug
    color: ee0701
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: help wanted
    color: 128A0C
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: wontfix
    color: ffffff
  - name: greenkeeper
    color: 00c775
branches:
  - name: master
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: true
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks: null
      restrictions: null
      enforce_admins: true
  - name: stage
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
