openapi: 3.0.0
info:
  version: '1.0.0'
  title: Rubrics
  description: App to help teachers create their rubrics
servers:
  - url: /api/v1
    description: Local Server
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/rhigleyfs/Rubrics/1.0.0
paths:
  /courses:
    get:
      summary: List All Courses For a User
      tags:
        - Courses
      security:
        - JWT: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
    post:
      summary: Create a New Course
      tags:
        - Courses
      security:
        - JWT: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
            examples:
              Example:
                value:
                  title: DWA
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
  '/courses/{id}':
    parameters:
      - name: id
        in: path
        required: true
        description: Course Id
        schema:
          type: string
    get:
      summary: Get One Course
      tags:
        - Courses
      security:
        - JWT: []
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Course'
    put:
      summary: Update one Course
      tags:
        - Courses
      security:
        - JWT: []
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/Course'
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Course'
    delete:
      summary: Delete one course
      tags:
        - Courses
      security:
        - JWT: []
      responses:
        '200':
          description: ''
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: string
          example: 3e836f45-5f86-4a9a-a27b-17e71b60317d
        title:
          type: string
          example: WAI
        createdAt:
          type: string
          example: '2019-08-05T08:40:51.620Z'
        updatedAt:
          type: string
          example: '2019-08-05T08:40:51.620Z'
      required:
        - id
        - title
        - createdAt
        - updatedAt
    Rubric:
      type: object
      properties:
        votes:
          type: integer
        choice:
          type: string
      required:
        - votes
        - choice
  securitySchemes:
    JWT:
      type: http
      scheme: Bearer
      description: ''