blank_issues_enabled: false
contact_links:
  - name: Examples
    url: https://gist.github.com/rhigleyfs/ccb08aedbcae2433a5349ad013ef1bea
    about: Check out these example issues for inspiration
  - name: Merge to Stage
    url: ./compare/stage...dev?template=dev.md&quick_pull=1&project=1
    about: When you are ready to merge into stage
